name: persian_linear_date_picker
description: Persian Linear Date Picker.
version: 0.0.1
homepage: https://github.com/pouyamaroufi

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  shamsi_date: ^1.0.1
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

